---

dist: trusty
sudo: required
python: 2.7
language: python
addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible
  - pip install ansible-review

before_script:
  - ansible --version
  - ansible-review --version
  - python --version

script:
  - printf '[defaults]\nroles_path=../' >ansible.cfg
  - git ls-files | grep -Ei '^[^[:punct:]].+.(yaml|yml)$' | xargs ansible-review -q
  - ansible-playbook --check --diff -i localhost, -c local tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
